import NavigationBar from '@/components/NavigationBar';
import './globals.css';
import PageFooter from '@/components/PageFooter';
import { Footer } from 'flowbite-react';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen	">
        <NavigationBar />
        {children}
        <PageFooter />
      </body>
    </html>
  );
}
